### ISSUE TITLE
Master not discovered exception

### ISSUE THREAD

**Issue by MaxKavun** [lean-delivery/ansible-role-elasticsearch#13]
##### SUMMARY
Master not discovered exception

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
elasticsearch.yml

##### ANSIBLE VERSION
ansible 2.9
```

```

##### CONFIGURATION
---
- hosts: localhost
  become: true
  roles:
  - role: ansible-role-java
  - role: ansible-role-elasticsearch
  vars:
    elastic_branch: 7

##### OS / ENVIRONMENT
ubuntu 18.04

##### STEPS TO REPRODUCE
Install Java & ElasticSearch roles

##### EXPECTED RESULTS
All works as should

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/9487402/69617662-9368d700-1049-11ea-84d1-64a1fcf7a14f.png)

```

```

**Comment by tgadiev** [comment]
Fixed by #19
